#management:
#  server:
#    port: 8093
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: "always"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/horses
    username: porker
    password: porker

logging:
  trace: true # Set to true to enable trace logging. Note: This will log teh response body of all requests, so if the code attempts to read teh response body it will throw exception as can only be read once.
  level:
    com:
      porkerspicks: info
    org:
      springframework:
        security: info
  file:
    name: c:/dev/logs/ppbf-dev.log

file:
  basePath: "C:\\dev\\betfair\\json\\"

debug: false
