package com.porkerspicks.ppbf.betfair.enums;

public enum CountryCode {
    AF("Afghanistan", "AFG"),
    AL("Albania", "ALB"),
    DZ("Algeria", "DZA"),
    AS("American Samoa", "ASM"),
    AD("Andorra", "AND"),
    AO("Angola", "AGO"),
    AG("Antigua and Barbuda", "ATG"),
    AR("Argentina", "ARG"),
    AM("Armenia", "ARM"),
    AU("Australia", "AUS"),
    AT("Austria", "AUT"),
    AZ("Azerbaijan", "AZE"),
    BS("Bahamas", "BHS"),
    BH("Bahrain", "BHR"),
    BD("Bangladesh", "BGD"),
    BB("Barbados", "BRB"),
    BY("Belarus", "BLR"),
    BE("Belgium", "BEL"),
    BZ("Belize", "BLZ"),
    BJ("Benin", "BEN"),
    BM("Bermuda", "BMU"),
    BT("Bhutan", "BTN"),
    BO("Bolivia", "BOL"),
    BA("Bosnia and Herzegovina", "BIH"),
    BW("Botswana", "BWA"),
    BR("Brazil", "BRA"),
    BN("Brunei Darussalam", "BRN"),
    BG("Bulgaria", "BGR"),
    BF("Burkina Faso", "BFA"),
    BI("Burundi", "BDI"),
    CV("Cabo Verde", "CPV"),
    KH("Cambodia", "KHM"),
    CM("Cameroon", "CMR"),
    CA("Canada", "CAN"),
    KY("Cayman Islands", "CYM"),
    CF("Central African Republic", "CAF"),
    TD("Chad", "TCD"),
    CL("Chile", "CHL"),
    CN("China", "CHN"),
    CO("Colombia", "COL"),
    KM("Comoros", "COM"),
    CG("Congo", "COG"),
    CD("Congo (Democratic Republic of the)", "COD"),
    CR("Costa Rica", "CRI"),
    CI("Côte d'Ivoire", "CIV"),
    HR("Croatia", "HRV"),
    CU("Cuba", "CUB"),
    CY("Cyprus", "CYP"),
    CZ("Czechia", "CZE"),
    DK("Denmark", "DNK"),
    DJ("Djibouti", "DJI"),
    DM("Dominica", "DMA"),
    DO("Dominican Republic", "DOM"),
    EC("Ecuador", "ECU"),
    EG("Egypt", "EGY"),
    SV("El Salvador", "SLV"),
    GQ("Equatorial Guinea", "GNQ"),
    ER("Eritrea", "ERI"),
    EE("Estonia", "EST"),
    SZ("Eswatini", "SWZ"),
    ET("Ethiopia", "ETH"),
    FJ("Fiji", "FJI"),
    FI("Finland", "FIN"),
    FR("France", "FRA"),
    GA("Gabon", "GAB"),
    GM("Gambia", "GMB"),
    GE("Georgia", "GEO"),
    DE("Germany", "DEU"),
    GH("Ghana", "GHA"),
    GR("Greece", "GRC"),
    GD("Grenada", "GRD"),
    GT("Guatemala", "GTM"),
    GN("Guinea", "GIN"),
    GW("Guinea-Bissau", "GNB"),
    GY("Guyana", "GUY"),
    HT("Haiti", "HTI"),
    HN("Honduras", "HND"),
    HU("Hungary", "HUN"),
    IS("Iceland", "ISL"),
    IN("India", "IND"),
    ID("Indonesia", "IDN"),
    IR("Iran (Islamic Republic of)", "IRN"),
    IQ("Iraq", "IRQ"),
    IE("Ireland", "IRL"),
    IL("Israel", "ISR"),
    IT("Italy", "ITA"),
    JM("Jamaica", "JAM"),
    JP("Japan", "JPN"),
    JO("Jordan", "JOR"),
    KZ("Kazakhstan", "KAZ"),
    KE("Kenya", "KEN"),
    KI("Kiribati", "KIR"),
    KP("Korea (Democratic People's Republic of)", "PRK"),
    KR("Korea (Republic of)", "KOR"),
    KW("Kuwait", "KWT"),
    KG("Kyrgyzstan", "KGZ"),
    LA("Lao People's Democratic Republic", "LAO"),
    LV("Latvia", "LVA"),
    LB("Lebanon", "LBN"),
    LS("Lesotho", "LSO"),
    LR("Liberia", "LBR"),
    LY("Libya", "LBY"),
    LI("Liechtenstein", "LIE"),
    LT("Lithuania", "LTU"),
    LU("Luxembourg", "LUX"),
    MG("Madagascar", "MDG"),
    MW("Malawi", "MWI"),
    MY("Malaysia", "MYS"),
    MV("Maldives", "MDV"),
    ML("Mali", "MLI"),
    MT("Malta", "MLT"),
    MH("Marshall Islands", "MHL"),
    MR("Mauritania", "MRT"),
    MU("Mauritius", "MUS"),
    MX("Mexico", "MEX"),
    FM("Micronesia (Federated States of)", "FSM"),
    MD("Moldova (Republic of)", "MDA"),
    MC("Monaco", "MCO"),
    MN("Mongolia", "MNG"),
    ME("Montenegro", "MNE"),
    MA("Morocco", "MAR"),
    MZ("Mozambique", "MOZ"),
    MM("Myanmar", "MMR"),
    NA("Namibia", "NAM"),
    NR("Nauru", "NRU"),
    NP("Nepal", "NPL"),
    NL("Netherlands", "NLD"),
    NZ("New Zealand", "NZL"),
    NI("Nicaragua", "NIC"),
    NE("Niger", "NER"),
    NG("Nigeria", "NGA"),
    MK("North Macedonia", "MKD"),
    NO("Norway", "NOR"),
    OM("Oman", "OMN"),
    PK("Pakistan", "PAK"),
    PW("Palau", "PLW"),
    PA("Panama", "PAN"),
    PG("Papua New Guinea", "PNG"),
    PY("Paraguay", "PRY"),
    PE("Peru", "PER"),
    PH("Philippines", "PHL"),
    PL("Poland", "POL"),
    PT("Portugal", "PRT"),
    QA("Qatar", "QAT"),
    RO("Romania", "ROU"),
    RU("Russian Federation", "RUS"),
    RW("Rwanda", "RWA"),
    KN("Saint Kitts and Nevis", "KNA"),
    LC("Saint Lucia", "LCA"),
    VC("Saint Vincent and the Grenadines", "VCT"),
    WS("Samoa", "WSM"),
    SM("San Marino", "SMR"),
    ST("Sao Tome and Principe", "STP"),
    SA("Saudi Arabia", "SAU"),
    SN("Senegal", "SEN"),
    RS("Serbia", "SRB"),
    SC("Seychelles", "SYC"),
    SL("Sierra Leone", "SLE"),
    SG("Singapore", "SGP"),
    SK("Slovakia", "SVK"),
    SI("Slovenia", "SVN"),
    SB("Solomon Islands", "SLB"),
    SO("Somalia", "SOM"),
    ZA("South Africa", "ZAF"),
    SS("South Sudan", "SSD"),
    ES("Spain", "ESP"),
    LK("Sri Lanka", "LKA"),
    SD("Sudan", "SDN"),
    SR("Suriname", "SUR"),
    SE("Sweden", "SWE"),
    CH("Switzerland", "CHE"),
    SY("Syrian Arab Republic", "SYR"),
    TJ("Tajikistan", "TJK"),
    TZ("Tanzania (United Republic of)", "TZA"),
    TH("Thailand", "THA"),
    TL("Timor-Leste", "TLS"),
    TG("Togo", "TGO"),
    TO("Tonga", "TON"),
    TT("Trinidad and Tobago", "TTO"),
    TN("Tunisia", "TUN"),
    TR("Turkey", "TUR"),
    TM("Turkmenistan", "TKM"),
    TV("Tuvalu", "TUV"),
    UG("Uganda", "UGA"),
    UA("Ukraine", "UKR"),
    AE("United Arab Emirates", "ARE"),
    GB("United Kingdom of Great Britain and Northern Ireland", "GBR"),
    US("United States of America", "USA"),
    UY("Uruguay", "URY"),
    UZ("Uzbekistan", "UZB"),
    VU("Vanuatu", "VUT"),
    VE("Venezuela (Bolivarian Republic of)", "VEN"),
    VN("Viet Nam", "VNM"),
    YE("Yemen", "YEM"),
    ZM("Zambia", "ZMB"),
    ZW("Zimbabwe", "ZWE");

    private final String countryName;
    private final String alpha3Code;

    CountryCode(String countryName, String alpha3Code) {
        this.countryName = countryName;
        this.alpha3Code = alpha3Code;
    }

    public String getCountryName() {
        return countryName;
    }

    public String getAlpha3Code() {
        return alpha3Code;
    }

    @Override
    public String toString() {
        return name() + " (" + countryName + ", " + alpha3Code + ")";
    }
}