spring:
  datasource:
    url: jdbc:mysql://localhost:3306/horses
    username: porker
    password: 4Norrie!

logging:
  trace: false # Set to true to enable trace logging. Note: This will log teh response body of all requests, so if the code attempts to read teh response body it will throw exception as can only be read once.
  file:
    name: c:/dev/logs/porkerspicks.log
    level: debug

server:
  port: 8080
  
betfair:
  keyStore:
    path: C:\dev\openssl\client-2048.p12
    password: norrie

azure:
  #connection-string: DefaultEndpointsProtocol=https;AccountName=porkerspicks;AccountKey=3QJ
  connection-string: AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
debug: false